### ISSUE TITLE
Preserve Git History

### ISSUE THREAD

**Issue by PuercoPop** [s-expressionists/Ecclesia#2]
It would be nice if you preserve the history of the code from when it was part of SICL. Using git filter-branch you can achieve that. The following command will keep only the commits that affected the sub-directory in question and turn that sub-directory the new top-level one.

```shell
$ git filter-branch --prune-empty --subdirectory-filter Code/Cleavir/Code-utilities/ master
```

**Comment by phoe** [comment]
Thanks - I will do this and force-push this repository.

**Comment by phoe** [comment]
9fa25d8f6
